# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meue.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexcelhebing = QtWidgets.QAction(MainWindow)
        self.actionexcelhebing.setObjectName("actionexcelhebing")
        self.actionabout_app = QtWidgets.QAction(MainWindow)
        self.actionabout_app.setObjectName("actionabout_app")
        self.actionabout_author = QtWidgets.QAction(MainWindow)
        self.actionabout_author.setObjectName("actionabout_author")
        self.actionmoney = QtWidgets.QAction(MainWindow)
        self.actionmoney.setObjectName("actionmoney")
        self.menu.addAction(self.actionexcelhebing)
        self.menu_2.addAction(self.actionabout_app)
        self.menu_2.addAction(self.actionabout_author)
        self.menu_2.addAction(self.actionmoney)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.excelhebing(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "良品工具箱"))
        self.menu.setTitle(_translate("MainWindow", "工具"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.actionexcelhebing.setText(_translate("MainWindow", "excel合并"))
        self.actionabout_app.setText(_translate("MainWindow", "关于软件"))
        self.actionabout_author.setText(_translate("MainWindow", "关于作者"))
        self.actionmoney.setText(_translate("MainWindow", "捐赠"))

    def excelhebing(self, MainWindow):
        MainWindow.items = QDockWidget('excel表格合并')
        MainWindow.items.resize(600, 800)
        # 设置窗口内的东西
        MainWindow.listWidget = QListWidget()
        MainWindow.listWidget.addItem('item1')
        MainWindow.items.setWidget(MainWindow.listWidget)
        MainWindow.items.setFloating(False)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, MainWindow.items)
